#!/usr/bin/bash
read -p "What path are you looking into? " Directory
if [ -e "$Directory" ]; then
        echo "This path exists."
else
        echo "This path does not exist."
        exit
fi
prompt_yes_no () {
        local prompt_message="$1"
        while true; do
                echo -n "$prompt_message  (y/n): "
                read answer
                case "$answer" in
                [Yy]* ) return 0;;
                [Nn]* ) return 1;;
                * ) echo  "Please answer yes or no.";;
                esac
        done
}
if prompt_yes_no "Can I take you there now? "; then
        cd "$Directory"
else
        echo "Thank you. Have a good day."
fi
